processing directory: '/processing/bvi_rnaseq'
reads fofn: '/example/reads.fofn'
transcriptome ref: '/example/transcripts.fa.ndx'
multiqc title: 'BVI RNA-seq'
multiqc description: 'Initial metric review of sets #1 and #2.'
sample key: '/example/sample_key.tsv'
kraken db: '/example/krakenDB/16S_Greengenes_k2db'
