processing directory: '/storage1/fs1/PTB/Active/twylieAnalysis/cleanupRNASeq/results'
reads fofn: '/storage1/fs1/PTB/Active/twylieAnalysis/cleanupRNASeq/reads.fofn'
transcriptome ref: '/storage1/fs1/PTB/Active/twylieAnalysis/bviRNASeq/analysisReview/transcriptome_reference/Homo_sapiens.GRCh38.cdna.all.fa.index'
multiqc title: 'RNA-seq Double-Clean-Up Experiment #1'
multiqc description: 'Review of clean-up conditions for RNA-seq libraries.'
sample key: '/storage1/fs1/PTB/Active/twylieAnalysis/cleanupRNASeq/sample_key.tsv'
kraken db: '/storage1/fs1/kwylie/Active/KRAKEN/STANDARD'
